algorithm:
  policy: CustomMultiInputPolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          mlp_layer: [192]

    net_arch:
      pi: [192, 96]
      vf: [192, 96]
    activation_fn: relu
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: False
  learning_rate: 0.001
  device: cuda
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 5
  n_steps: 256
  batch_size: 25600
  verbose: 1

learn:
  total_timesteps: 20000000

test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: {}


