algorithm:
  policy: CustomMultiInputPolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [512]
#          layer: []

    net_arch:
      pi: [512, 256]
      vf: [512, 256]
    activation_fn: relu
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: False
  learning_rate: 0.0003
  device: cuda
  gamma: 0.98
  gae_lambda: 0.95
  n_epochs: 5
  n_steps: 256
  batch_size: 65536
  verbose: 1
  scene_freq: 3000000

learn:
  total_timesteps: 25000000

test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: {}


