algorithm:
  policy: SimplePolicy
  policy_kwargs:
    features_extractor_class: FlexibleExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [512]
#          bn: True
#        depth:
#          channel: [ 32, 64, 128, 256 ]
#          kernel_size: 4
#          stride: 2
#          padding: 1
#          layer: [ ]
#          ln: True
#          bias: False

    critic:
      dist: mse
      n_critics: 2
      net_arch:
        layer: [512, 256]
#        bn: True
    actor:
      dist: normal
      net_arch:
        layer: [512, 256]
#        bn: True

    activation_fn: relu
    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: False

  learning_rate: 0.001
  horizon: 96
  tau: 0.005
  gamma: 0.99
  device: cuda
  gradient_steps: 10
  train_freq: 48
  batch_size: 25600
  actor_gradient_steps: 1
  buffer_size: 100
  ent_coef: 0.0003
  scene_freq: 3000000

learn:
  total_timesteps: 25000000
#  log_interval: 1

test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: { }