algorithm:
  device: cuda
  actor_batch_size: 128
  gradient_steps: 10
  actor_gradient_steps: 1
  batch_size: 16
  batch_length: 128
  H: 96
  ent_coef: 0.0000
  buffer_size: 400000
  train_freq: 48
  tau: 0.005
  gamma: 0.99

  world_kwargs:
    reward_EMA: True
    activation_fn: leaky_relu
    deter_dim: 512
    stoch_dim: 32
    hidden_dim: 512
    unimix_ratio: 0.01
    discrete: 32

    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001
      lr: 0.0001

    sequence_model_kwargs:
      initial: learned
      recurrent_class: GRUCell
      action_net_arch:
        layer: []
#        ln: True
      stoch_net_arch:
        layer: []
      in_net_arch:
        layer: []
        ln: True
        bias: False
      out_net_arch:
        layer: []
        ln: True
        bias: False

    encoder_kwargs:
      feature_extractor_kwargs:
        state:
          layer: [512]
          ln: True
      deter_net_arch:
        layer: []
      net_arch:
        layer: []
        ln: True
        bias: False

    reward_predictor_kwargs:
      dist: symlog_disc
      net_arch:
          layer: [512]
          ln: True
          bias: False

    continue_predictor_kwargs:
      dist: bernoulli
      net_arch:
        layer: [512, 512]
        ln: True
        bias: False

    decoder_kwargs:
      state:
        dist: symlog_mse
        net_arch:
          layer: [512, 512]
          ln: True

  policy_kwargs:
    share_features_extractor: False
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [512]
          # ln: True
        latent:
          layer: [256]
        #   # ln: True
    critic:
      dist: mse
      n_critics: 2
      net_arch:
        layer: [512, 512]
        # ln: True
    actor:
      dist: normal
#      squash_output: False
      net_arch:
        layer: [512, 512]
        # ln: True

#    ln: True
    activation_fn: leaky_relu
    optimizer_class: adamW
    optimizer_kwargs:
      # lr: 0.0002
      weight_decay: 0.00001
    share_features_extractor: False

  learning_rate:
    class: exponential
    kwargs:
      initial: 0.0001
      decay: 0.1
#    share_features_extractor: True

  loss_scale:
    dyn_scale: 0.5  # prior approaching post
    rep_scale: 0.1  # post approaching prior
    reward_scale: 0.0
    continue_scale: 0.0
    min_kl: 1.0
    decoder_scale:
      state: 1

  scene_freq: 3000000

learn:
    total_timesteps: 100000000
    log_interval: 1000

load: 
  only_load_world: False

test:
  is_fig_save: True
  is_video_save: True
  render_kwargs: { }