algorithm:
  policy: SimplePolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [512]

    critic:
      dist: mse
      n_critics: 1
      net_arch:
        layer: [512, 512]
    actor:
      dist: normal
      net_arch:
        layer: [512, 512]

    activation_fn: relu
    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001

  learning_rate: 0.0003
  n_epochs: 10
  batch_size: 32768
  n_steps: 4096
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  device: cuda

# Learning/training parameters
learn:
  total_timesteps: 80000000
  log_interval: 20

# Test parameters (for evaluation mode)
test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: {}